version: "3.8"
services:
  pgvector-db:
    image: pgvector/pgvector:pg17
    container_name: pgvector-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mydb
    ports:
      - "11451:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d # 可放初始化 SQL
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgvector_data:
